replicaCount: 1

image:
  repository: ghcr.io/nutanix-cloud-native/ndb-operator/controller
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  kubeProxy:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
  controller:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
