{{- if eq .Values.createConfig true }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configName}}
  namespace: {{ .Release.Namespace }}
data:
  nutanix_config.json: |-
    {
      "prismCentral": {
        "address": "{{ .Values.prismCentralEndPoint}}",
        "port": {{ .Values.prismCentralPort }},
        "insecure": {{ .Values.prismCentralInsecure }},
        "credentialRef": {
          "kind": "secret",
          "name": "{{ .Values.secretName }}",
          "namespace": "{{ .Release.Namespace }}"
        },
        "additionalTrustBundle": {
          "kind": "ConfigMap",
          "name": "user-ca-bundle",
          "namespace": "{{ .Release.Namespace }}"
        }

      },
      "enableCustomLabeling": {{ .Values.enableCustomLabeling }},

{{- if eq .Values.topologyDiscovery.type "Categories" }}
      "topologyDiscovery": {
        "type": "Categories",
        "topologyCategories": {
          "regionCategory": "{{ .Values.topologyCategories.region }}",
          "zoneCategory": "{{ .Values.topologyCategories.zone }}"
        }
{{- else }}
      "topologyDiscovery": {
        "type": "Prism"
{{- end }}
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: {{ .Release.Namespace }}
binaryData:
  ca.crt: {{ .Values.prismCentralAdditionalTrustBundle }}
{{- end }}
