{{- if eq .Values.createSecret true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  credentials: |
    [
      {
        "type": "basic_auth", 
        "data": { 
          "prismCentral":{
            "username": "{{ .Values.username }}",
            "password": "{{ .Values.password }}"
          },
          "prismElements": null
        }
      }
    ]
{{- end }}