{{- if eq .Values.kindtest false }}
{{- if eq .Values.createSecret true }}


{{- $username := .Values.username | required "username is required to create secret." -}}
{{- $password := .Values.password | required "password is required to create secret." -}}
{{- $prismEndPoint := .Values.prismEndPoint | required "prismEndPoint is required to create secret." -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.peSecretName }}
  namespace: {{ .Release.Namespace }}
data:
  # base64 encoded prism-ip:prism-port:admin:password. 
  # E.g.: echo -n "10.83.0.91:9440:admin:mypassword" | base64
  key: {{ printf "%s:9440:%s:%s" .Values.prismEndPoint .Values.username .Values.password | b64enc}}
{{- end }}

{{- if eq .Values.createPrismCentralSecret true }}

{{- $pcUsername := .Values.pcUsername | required "pcUsername is required to create secret." -}}
{{- $pcPassword := .Values.pcPassword | required "pcPassword is required to create secret." -}}
{{- $prismCentralEndPoint := .Values.prismCentralEndPoint | required "prismCentralEndPoint is required to create secret." -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pcSecretName }}
  namespace: {{ .Release.Namespace }}
data:
  # base64 encoded prism-ip:prism-port:admin:password. 
  # E.g.: echo -n "10.83.0.91:9440:admin:mypassword" | base64
  key: {{ printf "%s:9440:%s:%s" .Values.prismCentralEndPoint .Values.pcUsername .Values.pcPassword | b64enc}}
{{- end }}
{{- end }}